---
kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: guestbook
  labels:
    app: guestbook
spec:
  replicas: 3
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - name: guestbook
        image: raelga/guestbook:latest
        ports:
        - name: http-server
          containerPort: 3000
