version: '3'

services:
  reverse-proxy:
    image: containous/traefik:experimental-v2.0
    restart: unless-stopped
    command:
    - "--api"
    - "--providers.docker"
    - "--entrypoints=Name:mongo Address::27017"
    ports:
      - "8080:8080"
      - "27017:27017"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mongo1:
    image: mongo
    hostname: mongo1.local
    restart: unless-stopped
    labels:
      - "traefik.tcp.routers.mongo.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.mongo.entrypoints=mongo"
